FROM python:3.9.0-alpine
# 删除不必要的静态文件和媒体文件
RUN rm -rf /path/to/static/files
RUN rm -rf /path/to/media/files
# 清理不使用的依赖库
RUN mkdir /app
COPY . /app 
COPY requirements.txt /app
RUN pip install -r /app/requirements.txt
RUN python /app/manage.py migrate
RUN python /app/manage.py makemigrations
WORKDIR /app
RUN pip uninstall unused-library
