# Generated by Django 4.2.4 on 2023-08-08 01:43

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='EmailVerifyCode',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('to_email_address', models.EmailField(blank=True, help_text='验证码接收邮箱', max_length=255, null=True, verbose_name='验证码接收邮箱')),
                ('verify_code', models.CharField(blank=True, help_text='邮箱验证码', max_length=255, null=True, verbose_name='邮箱验证码')),
                ('verified', models.CharField(choices=[('0', 'unused'), ('1', 'used')], default='0', help_text='是否使用 0 否 1 是', max_length=1, verbose_name='Status (*)')),
                ('verify_ip', models.CharField(blank=True, help_text='验证IP', max_length=255, null=True, verbose_name='验证IP')),
                ('expire_at', models.DateTimeField(auto_now_add=True, help_text='验证码过期时间', null=True, verbose_name='验证码过期时间')),
                ('biz_type', models.CharField(choices=[('0', 'unused'), ('1', 'used')], default='10', help_text='注册认证', max_length=2, verbose_name='Status (*)')),
                ('update_datetime', models.DateTimeField(auto_now=True, help_text='修改时间', null=True, verbose_name='修改时间')),
                ('create_datetime', models.DateTimeField(auto_now_add=True, help_text='创建时间', null=True, verbose_name='创建时间')),
            ],
            options={
                'verbose_name': '邮箱验证码核销记录表',
                'verbose_name_plural': '邮箱验证码核销记录表',
                'db_table': 'email_verify_code',
                'ordering': ('-create_datetime',),
            },
        ),
        migrations.CreateModel(
            name='FrontUserBase',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nickname', models.CharField(blank=True, help_text='用户昵称', max_length=255, null=True, verbose_name='用户昵称')),
                ('description', models.CharField(blank=True, help_text='描述', max_length=255, null=True, verbose_name='描述')),
                ('avatar_version', models.CharField(blank=True, help_text='头像版本', max_length=255, null=True, verbose_name='头像版本')),
                ('last_login_ip', models.CharField(blank=True, help_text='上一次登录IP', max_length=255, null=True, verbose_name='上一次登录IP')),
                ('update_datetime', models.DateTimeField(auto_now=True, help_text='修改时间', null=True, verbose_name='修改时间')),
                ('create_datetime', models.DateTimeField(auto_now_add=True, help_text='创建时间', null=True, verbose_name='创建时间')),
            ],
            options={
                'verbose_name': '前端用户基础信息表',
                'verbose_name_plural': '前端用户基础信息表',
                'db_table': 'front_user_base',
                'ordering': ('-create_datetime',),
            },
        ),
        migrations.CreateModel(
            name='FrontUserExtraEmail',
            fields=[
                ('identity', models.AutoField(primary_key=True, serialize=False)),
                ('username', models.EmailField(blank=True, help_text='登录邮箱', max_length=255, null=True, verbose_name='登录邮箱')),
                ('password', models.CharField(blank=True, help_text='密码', max_length=255, null=True, verbose_name='登录密码')),
                ('salt', models.CharField(blank=True, help_text='密码盐值', max_length=255, null=True, verbose_name='密码盐值')),
                ('verified', models.CharField(choices=[('0', 'unverified'), ('1', 'verified')], default='0', help_text='是否验证 0 否 1 是', max_length=1, verbose_name='Status (*)')),
                ('update_datetime', models.DateTimeField(auto_now=True, help_text='修改时间', null=True, verbose_name='修改时间')),
                ('create_datetime', models.DateTimeField(auto_now_add=True, help_text='创建时间', null=True, verbose_name='创建时间')),
            ],
            options={
                'verbose_name': '用户邮箱注册表',
                'verbose_name_plural': '用户邮箱注册表',
                'db_table': 'front_user_extra_email',
                'ordering': ('-create_datetime',),
            },
        ),
    ]
