# Generated by Django 4.2.4 on 2023-08-08 02:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chatgpt_user', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='FrontUserExtraBinding',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('binding_type', models.CharField(blank=True, help_text='绑定类型,qq,wechat,sina,github,email,phone', max_length=32, null=True, verbose_name='绑定类型,qq,wechat,sina,github,email,phone')),
                ('extra_info_id', models.IntegerField(blank=True, help_text='额外信息表ID', null=True, verbose_name='额外信息表ID')),
                ('base_user_id', models.IntegerField(blank=True, help_text='基础用户表的ID', null=True, verbose_name='基础用户表的ID')),
                ('update_datetime', models.DateTimeField(auto_now=True, help_text='修改时间', null=True, verbose_name='修改时间')),
                ('create_datetime', models.DateTimeField(auto_now_add=True, help_text='创建时间', null=True, verbose_name='创建时间')),
            ],
            options={
                'verbose_name': '前端用户绑定表',
                'verbose_name_plural': '前端用户绑定表',
                'db_table': 'front_user_extra_binding',
                'ordering': ('-create_datetime',),
            },
        ),
        migrations.CreateModel(
            name='SysEmailSendLog',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('from_email_address', models.EmailField(blank=True, help_text='发件人邮箱', max_length=64, null=True, verbose_name='发件人邮箱')),
                ('to_email_address', models.EmailField(blank=True, help_text='验证码接收邮箱', max_length=64, null=True, verbose_name='验证码接收邮箱')),
                ('biz_type', models.CharField(choices=[('10', '注册认证'), ('11', '找回密码认证')], default='10', help_text='注册认证', max_length=2, verbose_name='Status (*)')),
                ('request_ip', models.CharField(blank=True, help_text='请求IP', max_length=32, null=True, verbose_name='请求IP')),
                ('content', models.TextField(blank=True, help_text='发送内容', null=True, verbose_name='发送内容')),
                ('message_id', models.CharField(blank=True, help_text='发送后会返回一个messageId', max_length=128, null=True, verbose_name='发送后会返回一个messageId')),
                ('status', models.CharField(choices=[('1', '发送成功'), ('0', '发送失败')], default='0', help_text='发送状态，0失败，1成功', max_length=1, verbose_name='Status (*)')),
                ('message', models.CharField(blank=True, help_text='发送后的消息，用于记录成功/失败的信息，成功默认为success', max_length=255, null=True, verbose_name='发送后的消息，用于记录成功/失败的信息，成功默认为success')),
                ('create_datetime', models.DateTimeField(auto_now_add=True, help_text='创建时间', null=True, verbose_name='创建时间')),
                ('update_datetime', models.DateTimeField(auto_now=True, help_text='修改时间', null=True, verbose_name='修改时间')),
            ],
            options={
                'verbose_name': '邮箱发送日志',
                'verbose_name_plural': '邮箱发送日志',
                'db_table': 'sys_email_send_log',
                'ordering': ('-create_datetime',),
            },
        ),
        migrations.CreateModel(
            name='SysFrontUserLoginLog',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('base_user_id', models.IntegerField(blank=True, help_text='登录的基础用户ID', null=True, verbose_name='登录的基础用户ID')),
                ('login_type', models.CharField(blank=True, help_text='登录方式（注册方式）邮箱,手机', max_length=32, null=True, verbose_name='登录方式（注册方式）')),
                ('login_extra_info_id', models.IntegerField(help_text='登录信息ID与login_type有关联，邮箱登录时关联front_user_extra_email', null=True, verbose_name='登录信息ID与login_type有关联，邮箱登录时关联front_user_extra_email')),
                ('login_ip', models.CharField(blank=True, help_text='登录的IP地址', max_length=32, null=True, verbose_name='登录的IP地址')),
                ('login_status', models.CharField(choices=[('1', '登录成功'), ('0', '登录失败')], default='0', help_text='登录状态，1登录成功，0登录失败', max_length=1, verbose_name='Status (*)')),
                ('message', models.CharField(blank=True, help_text='结果，如果成功一律success；否则保存错误信息', max_length=64, null=True, verbose_name='结果，如果成功一律success；否则保存错误信息')),
                ('create_datetime', models.DateTimeField(auto_now_add=True, help_text='创建时间', null=True, verbose_name='创建时间')),
            ],
            options={
                'verbose_name': '前端用户登录日志表',
                'verbose_name_plural': '前端用户登录日志表',
                'db_table': 'sys_front_user_login_log',
                'ordering': ('-create_datetime',),
            },
        ),
        migrations.AlterField(
            model_name='emailverifycode',
            name='biz_type',
            field=models.CharField(choices=[('10', '注册认证'), ('11', '找回密码认证')], default='10', help_text='注册认证', max_length=2, verbose_name='Status (*)'),
        ),
        migrations.AlterField(
            model_name='emailverifycode',
            name='to_email_address',
            field=models.EmailField(blank=True, help_text='验证码接收邮箱', max_length=64, null=True, verbose_name='验证码接收邮箱'),
        ),
        migrations.AlterField(
            model_name='emailverifycode',
            name='verify_code',
            field=models.CharField(blank=True, help_text='邮箱验证码', max_length=64, null=True, verbose_name='邮箱验证码'),
        ),
        migrations.AlterField(
            model_name='emailverifycode',
            name='verify_ip',
            field=models.CharField(blank=True, help_text='验证IP', max_length=128, null=True, verbose_name='验证IP'),
        ),
        migrations.AlterField(
            model_name='frontuserbase',
            name='avatar_version',
            field=models.CharField(blank=True, help_text='头像版本', max_length=32, null=True, verbose_name='头像版本'),
        ),
        migrations.AlterField(
            model_name='frontuserbase',
            name='last_login_ip',
            field=models.CharField(blank=True, help_text='上一次登录IP', max_length=128, null=True, verbose_name='上一次登录IP'),
        ),
        migrations.AlterField(
            model_name='frontuserbase',
            name='nickname',
            field=models.CharField(blank=True, help_text='用户昵称', max_length=32, null=True, verbose_name='用户昵称'),
        ),
    ]
