# Generated by Django 4.2.4 on 2023-08-09 08:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chatgpt_user', '0002_frontuserextrabinding_sysemailsendlog_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='frontuserextraemail',
            old_name='identity',
            new_name='id',
        ),
    ]
