# Generated by Django 4.2.4 on 2023-08-10 11:22

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('captcha', '0002_alter_captchastore_id'),
        ('chatgpt_user', '0004_captchastore'),
    ]

    operations = [
        migrations.CreateModel(
            name='CustomerCaptchaStore',
            fields=[
                ('captchastore_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, to='captcha.captchastore')),
                ('pic_code_seesion_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
            ],
            bases=('captcha.captchastore',),
        ),
        migrations.DeleteModel(
            name='CaptchaStore',
        ),
    ]
