# Generated by Django 4.2.4 on 2023-08-13 11:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chatgpt_user', '0005_customercaptchastore_delete_captchastore'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='frontuserbase',
            options={'ordering': ('-create_datetime',), 'verbose_name': '用户基础信息表', 'verbose_name_plural': '用户基础信息表'},
        ),
        migrations.AlterField(
            model_name='emailverifycode',
            name='expire_at',
            field=models.DateTimeField(blank=True, help_text='验证码过期时间', null=True, verbose_name='验证码过期时间'),
        ),
        migrations.AlterField(
            model_name='frontuserextrabinding',
            name='binding_type',
            field=models.CharField(blank=True, default='email', help_text='绑定类型,qq,wechat,sina,github,email,phone', max_length=32, null=True, verbose_name='绑定类型,qq,wechat,sina,github,email,phone'),
        ),
        migrations.AlterField(
            model_name='frontuserextraemail',
            name='verified',
            field=models.IntegerField(choices=[('0', 'unverified'), ('1', 'verified')], default='0', help_text='是否验证 0 否 1 是', verbose_name='Status (*)'),
        ),
    ]
