# Generated by Django 4.2.4 on 2023-08-13 22:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chatgpt_user', '0007_alter_frontuserextraemail_managers_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='emailverifycode',
            name='verified',
        ),
    ]
