# Generated by Django 4.2.4 on 2023-08-14 09:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chatgpt_user', '0008_remove_emailverifycode_verified'),
    ]

    operations = [
        migrations.AddField(
            model_name='frontuserbase',
            name='username',
            field=models.EmailField(blank=True, help_text='登录邮箱', max_length=255, null=True, verbose_name='登录邮箱'),
        ),
    ]
