# Generated by Django 4.2.4 on 2023-09-01 22:28

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ChatMessage',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('username', models.EmailField(blank=True, help_text='用户名', max_length=64, null=True, verbose_name='用户名')),
                ('update_datetime', models.DateTimeField(auto_now=True, help_text='修改时间', null=True, verbose_name='修改时间')),
                ('create_datetime', models.DateTimeField(auto_now_add=True, help_text='创建时间', null=True, verbose_name='创建时间')),
            ],
            options={
                'verbose_name': '聊天消息表',
                'verbose_name_plural': '聊天消息表',
                'db_table': 'chat_message',
                'ordering': ('-create_datetime',),
            },
        ),
    ]
