# Generated by Django 4.2.4 on 2024-02-05 13:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chatgpt_chat', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='chatmessage',
            name='completion',
            field=models.TextField(blank=True, help_text='回复词', null=True, verbose_name='回复词'),
        ),
        migrations.AddField(
            model_name='chatmessage',
            name='completion_tokens',
            field=models.IntegerField(blank=True, help_text='提示语tokens', null=True, verbose_name='回复消耗tokens'),
        ),
        migrations.AddField(
            model_name='chatmessage',
            name='prompt',
            field=models.TextField(blank=True, help_text='提示语', null=True, verbose_name='提示语'),
        ),
        migrations.AddField(
            model_name='chatmessage',
            name='prompt_tokens',
            field=models.IntegerField(blank=True, help_text='提示语tokens', null=True, verbose_name='提示语消耗tokens'),
        ),
        migrations.AddField(
            model_name='chatmessage',
            name='total_tokens',
            field=models.IntegerField(blank=True, help_text='提示语tokens', null=True, verbose_name='总共消耗tokens'),
        ),
    ]
