# Generated by Django 4.2.4 on 2024-02-06 10:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chatgpt_chat', '0002_chatmessage_completion_chatmessage_completion_tokens_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='chatmessage',
            name='username',
        ),
        migrations.AddField(
            model_name='chatmessage',
            name='baseUserId',
            field=models.IntegerField(blank=True, help_text='用户名', null=True, verbose_name='用户名'),
        ),
        migrations.AlterField(
            model_name='chatmessage',
            name='completion_tokens',
            field=models.IntegerField(blank=True, help_text='回复词消耗tokens', null=True, verbose_name='回复词消耗tokens'),
        ),
        migrations.AlterField(
            model_name='chatmessage',
            name='prompt_tokens',
            field=models.IntegerField(blank=True, help_text='提示语消耗tokens', null=True, verbose_name='提示语消耗tokens'),
        ),
        migrations.AlterField(
            model_name='chatmessage',
            name='total_tokens',
            field=models.IntegerField(blank=True, help_text='总共消耗tokens', verbose_name='总共消耗tokens'),
        ),
    ]
