# Generated by Django 4.2.4 on 2024-02-09 18:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chatgpt_chat', '0004_chatmessage_created'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chatmessage',
            name='created',
            field=models.DateField(auto_now_add=True, help_text='创建日期', null=True, verbose_name='创建日期'),
        ),
    ]
