# Generated by Django 4.2.4 on 2024-02-13 16:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chatgpt_chat', '0005_alter_chatmessage_created'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chatmessage',
            name='total_tokens',
            field=models.IntegerField(blank=True, help_text='总共消耗tokens', null=True, verbose_name='总共消耗tokens'),
        ),
    ]
