# Generated by Django 4.2.4 on 2024-03-09 21:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chatgpt_chat', '0007_chatmessage_chat_model'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chatmessage',
            name='baseUserId',
            field=models.IntegerField(blank=True, help_text='用户ID', null=True, verbose_name='用户ID'),
        ),
    ]
