# Generated by Django 4.2.4 on 2024-03-24 15:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chatgpt_chat', '0008_alter_chatmessage_baseuserid'),
    ]

    operations = [
        migrations.AddField(
            model_name='chatmessage',
            name='completion_message',
            field=models.TextField(blank=True, help_text='详细回复词', null=True, verbose_name='详细回复词'),
        ),
    ]
