# Generated by Django 4.2.4 on 2024-04-06 14:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chatgpt_chat', '0009_chatmessage_completion_message'),
    ]

    operations = [
        migrations.RenameField(
            model_name='chatmessage',
            old_name='prompt',
            new_name='messages',
        ),
    ]
