# Generated by Django 4.2.4 on 2023-09-20 21:38

import chatgpt_image.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ImageMessage',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('username', models.EmailField(help_text='用户名', max_length=64, verbose_name='用户名')),
                ('prompt', models.CharField(help_text='提示语', max_length=255, verbose_name='提示语')),
                ('size', models.CharField(help_text='生成分辨率', max_length=255, verbose_name='生成分辨率')),
                ('number', models.CharField(help_text='生成数量', max_length=255, verbose_name='生成数量')),
                ('res_data', models.JSONField(null=True, verbose_name='data数据')),
                ('update_datetime', models.DateTimeField(auto_now=True, help_text='修改时间', null=True, verbose_name='修改时间')),
                ('create_datetime', models.DateTimeField(auto_now_add=True, help_text='创建时间', null=True, verbose_name='创建时间')),
            ],
            options={
                'verbose_name': '图片消息表',
                'verbose_name_plural': '图片消息表',
                'db_table': 'Image_message',
                'ordering': ('-create_datetime',),
            },
        ),
    ]
