# Generated by Django 4.2.4 on 2023-09-20 21:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chatgpt_image', '0002_filelist'),
    ]

    operations = [
        migrations.AddField(
            model_name='imagemessage',
            name='uuid',
            field=models.CharField(default='f112a23feaef45f595184e82fa18f2fe', help_text='唯一编码', max_length=255, verbose_name='唯一编码'),
            preserve_default=False,
        ),
    ]
