# Generated by Django 4.2.4 on 2024-02-09 18:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chatgpt_image', '0005_imagemessage_created'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='imagemessage',
            name='created',
        ),
    ]
