# Generated by Django 4.2.4 on 2024-02-13 17:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chatgpt_image', '0006_remove_imagemessage_created'),
    ]

    operations = [
        migrations.AddField(
            model_name='imagemessage',
            name='draw_model',
            field=models.CharField(blank=True, help_text='绘画模型', max_length=32, null=True, verbose_name='绘画模型'),
        ),
    ]
