# Generated by Django 4.2.4 on 2024-03-09 21:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chatgpt_image', '0009_rename_image_quality_imagemessage_imagequality'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='imagemessage',
            name='username',
        ),
        migrations.AddField(
            model_name='imagemessage',
            name='baseUserId',
            field=models.IntegerField(blank=True, help_text='用户ID', null=True, verbose_name='用户ID'),
        ),
        migrations.AlterField(
            model_name='imagemessage',
            name='number',
            field=models.IntegerField(blank=True, default=1, help_text='生成数量', null=True, verbose_name='生成数量'),
        ),
    ]
