# Generated by Django 4.2.4 on 2024-01-27 16:24

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Config',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('key', models.EmailField(blank=True, help_text='配置键', max_length=64, null=True, verbose_name='配置键')),
                ('value', models.EmailField(blank=True, help_text='配置值', max_length=64, null=True, verbose_name='配置值')),
                ('update_datetime', models.DateTimeField(auto_now=True, help_text='修改时间', null=True, verbose_name='修改时间')),
                ('create_datetime', models.DateTimeField(auto_now_add=True, help_text='创建时间', null=True, verbose_name='创建时间')),
            ],
            options={
                'verbose_name': '业务配置表',
                'verbose_name_plural': '业务配置表',
                'db_table': 'chatgpt_config',
                'ordering': ('-create_datetime',),
            },
        ),
    ]
