# Generated by Django 4.2.4 on 2024-01-27 16:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chatgpt_config', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='config',
            name='key',
            field=models.CharField(blank=True, help_text='配置键', max_length=64, null=True, verbose_name='配置键'),
        ),
        migrations.AlterField(
            model_name='config',
            name='value',
            field=models.CharField(blank=True, help_text='配置值', max_length=255, null=True, verbose_name='配置值'),
        ),
    ]
