# Generated by Django 4.2.4 on 2024-01-27 17:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chatgpt_config', '0003_config_describtion'),
    ]

    operations = [
        migrations.AddField(
            model_name='config',
            name='config_Code',
            field=models.CharField(blank=True, help_text='业务配置码', max_length=64, null=True, verbose_name='业务配置码'),
        ),
    ]
