# Generated by Django 4.2.4 on 2024-01-31 10:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chatgpt_config', '0004_config_config_code'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserConfig',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('customerId', models.IntegerField(blank=True, help_text='用户ID', null=True, verbose_name='用户ID')),
                ('key', models.CharField(blank=True, help_text='配置键', max_length=64, null=True, verbose_name='配置键')),
                ('value', models.CharField(blank=True, help_text='配置值', max_length=255, null=True, verbose_name='配置值')),
                ('describtion', models.CharField(blank=True, help_text='描述', max_length=255, null=True, verbose_name='描述')),
                ('create_datetime', models.DateTimeField(auto_now_add=True, help_text='创建时间', null=True, verbose_name='创建时间')),
                ('update_datetime', models.DateTimeField(auto_now=True, help_text='修改时间', null=True, verbose_name='修改时间')),
            ],
            options={
                'verbose_name': '用户配置表',
                'verbose_name_plural': '用户配置表',
                'db_table': 'user_config',
                'ordering': ('-create_datetime',),
            },
        ),
    ]
