# Generated by Django 4.2.4 on 2024-01-31 18:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chatgpt_config', '0005_userconfig'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userconfig',
            name='describtion',
            field=models.CharField(help_text='描述', max_length=255, null=True, verbose_name='描述'),
        ),
        migrations.AlterField(
            model_name='userconfig',
            name='key',
            field=models.CharField(help_text='配置键', max_length=64, null=True, verbose_name='配置键'),
        ),
        migrations.AlterField(
            model_name='userconfig',
            name='value',
            field=models.CharField(help_text='配置值', max_length=255, null=True, verbose_name='配置值'),
        ),
    ]
