# Generated by Django 4.2.4 on 2024-02-01 08:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chatgpt_config', '0006_alter_userconfig_describtion_alter_userconfig_key_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userconfig',
            old_name='describtion',
            new_name='chatModel',
        ),
        migrations.RenameField(
            model_name='userconfig',
            old_name='value',
            new_name='proxyAdress',
        ),
        migrations.RenameField(
            model_name='userconfig',
            old_name='key',
            new_name='secretKey',
        ),
        migrations.AddField(
            model_name='userconfig',
            name='drawvalue',
            field=models.CharField(help_text='描述', max_length=255, null=True, verbose_name='描述'),
        ),
    ]
