# Generated by Django 4.2.4 on 2024-02-09 18:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chatgpt_config', '0008_rename_customerid_userconfig_baseuserid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='config',
            name='config_Code',
            field=models.CharField(blank=True, choices=[('openai_chat_api_3_5', '3.5会话配置项'), ('openai_chat_api_4', '4.0会话配置项'), ('openai_image_api_DALL_E_2', 'Dall2绘图配置项'), ('openai_image_api_DALL_E_3', 'Dall3绘图配置项'), ('email_config', '邮箱服务器配置项')], default=10, help_text='业务配置码', max_length=64, null=True, verbose_name='业务配置码'),
        ),
    ]
