# Generated by Django 4.2.4 on 2024-02-25 11:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chatgpt_config', '0010_alter_userconfig_chatmodel_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userconfig',
            name='chatModel',
        ),
        migrations.AddField(
            model_name='userconfig',
            name='chatModels',
            field=models.CharField(choices=[('gpt-3.5-turbo', 'gpt-3.5-turbo'), ('gpt-4', 'gpt-4'), ('gpt-4-turbo-preview', 'gpt-4-turbo-preview')], default='gpt-3.5-turbo', help_text='对话模型', max_length=100, verbose_name='对话模型'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='config',
            name='config_Code',
            field=models.CharField(blank=True, choices=[('openai_chat_api_3_5', '3.5会话配置项'), ('openai_chat_api_4', '4.0会话配置项'), ('openai_image_api_DALL_E_2', 'Dall2绘图配置项'), ('openai_image_api_DALL_E_3', 'Dall3绘图配置项'), ('email_config', '邮箱服务器配置项'), ('customer_config', '自定义配置项')], default=10, help_text='业务配置码', max_length=64, null=True, verbose_name='业务配置码'),
        ),
    ]
