# Generated by Django 4.2.4 on 2024-02-25 19:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chatgpt_config', '0011_remove_userconfig_chatmodel_userconfig_chatmodels_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userconfig',
            name='chatModels',
        ),
        migrations.AddField(
            model_name='userconfig',
            name='chatModel',
            field=models.CharField(default='gpt-3.5-turbo', help_text='对话模型', max_length=100, verbose_name='对话模型'),
            preserve_default=False,
        ),
    ]
