# Generated by Django 4.2.4 on 2024-02-25 19:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chatgpt_config', '0012_remove_userconfig_chatmodels_userconfig_chatmodel'),
    ]

    operations = [
        migrations.AddField(
            model_name='userconfig',
            name='content',
            field=models.JSONField(default={'disabled': 'true', 'label': 'gpt-3.5-turbo', 'value': 'gpt-3.5-turbo'}),
        ),
    ]
