# Generated by Django 4.2.4 on 2024-02-25 20:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chatgpt_config', '0014_alter_userconfig_drawvalue_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userconfig',
            name='content',
            field=models.JSONField(default='{\n            "label": "gpt-3.5-turbo",\n            "value": \'gpt-3.5-turbo\',\n            "disabled": "true"\n          }'),
        ),
    ]
