# Generated by Django 4.2.4 on 2024-02-25 20:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chatgpt_config', '0017_alter_userconfig_content'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userconfig',
            name='content',
            field=models.JSONField(default=dict, verbose_name='对话模型'),
        ),
    ]
