# Generated by Django 4.2.4 on 2024-02-25 20:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chatgpt_config', '0018_alter_userconfig_content'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userconfig',
            old_name='content',
            new_name='chatModelList',
        ),
    ]
