# Generated by Django 4.2.4 on 2024-03-09 21:19

import chatgpt_config.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chatgpt_config', '0020_alter_userconfig_chatmodellist'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userconfig',
            name='chatModel',
            field=models.CharField(default='gpt-3.5-turbo', help_text='对话模型', max_length=100, verbose_name='对话模型'),
        ),
        migrations.AlterField(
            model_name='userconfig',
            name='chatModelList',
            field=models.JSONField(default=chatgpt_config.models.get_chatModel_list, help_text='"disabled": "fasle" 则为无权限', verbose_name='权限列表'),
        ),
        migrations.AlterField(
            model_name='userconfig',
            name='drawvalue',
            field=models.CharField(blank=True, default='dall-e-2', help_text='绘画模型', max_length=255, null=True, verbose_name='绘画模型'),
        ),
        migrations.AlterField(
            model_name='userconfig',
            name='proxyAdress',
            field=models.CharField(blank=True, default='', help_text='配置值', max_length=255, null=True, verbose_name='配置值'),
        ),
        migrations.AlterField(
            model_name='userconfig',
            name='secretKey',
            field=models.CharField(blank=True, default='', help_text='配置键', max_length=64, null=True, verbose_name='配置键'),
        ),
    ]
