# Generated by Django 4.2.4 on 2024-05-02 10:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chatgpt_config', '0021_alter_userconfig_chatmodel_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='config',
            name='config_Code',
            field=models.CharField(blank=True, choices=[('openai_config', 'OpenAI配置项'), ('claude_config', 'Claude配置项'), ('email_config', '邮箱服务器配置项'), ('customer_config', '自定义配置项')], default=10, help_text='业务配置码', max_length=64, null=True, verbose_name='业务配置码'),
        ),
    ]
